# Generated by Django 5.1.1 on 2024-09-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
