# Generated by Django 5.1.1 on 2024-10-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_is_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_starred',
        ),
    ]
