# Generated by Django 5.1.1 on 2024-10-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_is_starred'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_starred',
            new_name='isStarred',
        ),
    ]
